parameters:
    xidea_organization.organization.repository.default.class: Xidea\Bundle\OrganizationBundle\Doctrine\ORM\Repository\OrganizationRepository
    xidea_organization.organization.loader.default.class: Xidea\Bundle\OrganizationBundle\Doctrine\ORM\Loader\OrganizationLoader
    xidea_organization.organization.manager.default.class: Xidea\Bundle\OrganizationBundle\Doctrine\ORM\Manager\OrganizationManager
  
services:
    xidea_organization.organization.repository.default:
        class: '%xidea_organization.organization.repository.default.class%'
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - '%xidea_organization.organization.class%'
    xidea_organization.organization.loader.default:
        class: '%xidea_organization.organization.loader.default.class%'
        arguments:
            - '@xidea_organization.organization.repository.default'
            - '@xidea_organization.organization.configuration'
            - '@xidea_base.paginator'
    xidea_organization.organization.manager.default:
        class: '%xidea_organization.organization.manager.default.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
