parameters:
    xidea_organization.organization.configuration.default.class: Xidea\Bundle\BaseBundle\Configuration
    xidea_organization.organization.factory.default.class: Xidea\Component\Base\Factory\ModelFactory
    xidea_organization.organization.template.configuration.default.class: Xidea\Bundle\BaseBundle\TemplateConfiguration
  
services:
    xidea_organization.organization.configuration.default:
        class: %xidea_organization.organization.configuration.default.class%
        arguments:
            - %xidea_organization.organization.code%
            - @xidea_organization.template.configuration
        tags:
            - { name: xidea_base.configuration }
    xidea_organization.organization.factory.default:
        class: %xidea_organization.organization.factory.default.class%
        arguments:
            - %xidea_organization.organization.class%